modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "dotarmorweapons"
version = "${version}"
displayName = "Dawn Of Time Armor and Weapons"
authors = "Me!"
description = '''
Dawn Of Time Armor and Weapons
'''
#logoFile = "logo.png"

[[dependencies.dotarmorweapons]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dotarmorweapons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dotarmorweapons]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"