modLoader="javafml"
loaderVersion="[45,)"
license="https://opensource.org/license/mit/"
issueTrackerURL="https://github.com/DawnOfTimeMC/dotarmorweapons/issues/"

[[mods]] #mandatory
    modId="dotarmorweapons"
    version="${file.jarVersion}"
    displayName="Dawn Of Time : Armor & Weapons"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dawn-of-time"
    logoFile="logo.png"
    credits="Mr_ch0c0late, Wonyu and Seynax"
    authors="Poulpinou & TheGoldenWorld"
    description='''
        This mod adds many armor and weapons from different cultures.
        '''

[[dependencies.dawnoftimebuilder]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
